/**
 * @flow
 */
export type VehicleCondition = {
  summary: string,
  buy_day: string,
  registration_day: string,
  plate_price: string,
  loan_pending_amount: number,
  loan_pending_terms: number,
  evaluated_price: string,
  chassis_state: string,
  buy_price: string,
  electric_state: string,
  vehicle_id: string,
  claims_amount: number,
  purchase_type: number,
  transmission_status: number[],
  loan_amount: number,
  has_claims_records: boolean,
  surface_status: number,
  is_electric_ok: boolean,
  assigned_day: string,
  has_navigation: boolean,
  power_kw: string,
  loan_terms: number,
  starter_status: number[],
  is_work_ok: number,
  is_leather: boolean,
  insurance_expired_day: string,
  created_at: string,
  certificate: number[],
  has_sunroof: boolean,
  evaluator: {
    created_at: string,
    id_no: string,
    avatar: string,
    mobile: string,
    id: string,
    name: string
  },
  engine_status: number[],
  collateral_times: number,
  is_chassis_ok: boolean,
  id: string,
  collateral_last_free: number,
  interior_status: number,
  mileage: number,
  exhaust_status: number[]
};
